[build]
builder = "NIXPACKS"

[deploy]
startCommand = "mkdir -p /app/img/profile_pic /app/uploads/items /app/uploads/deliveries /app/uploads/pickups /app/uploads/qr_codes && chmod -R 777 /app/uploads /app/img && node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
healthcheckPath = "/health.php"
healthcheckTimeout = 100
